stages:
  - build
  - deploy
###############################DEVELOP###########################################
build-develop:
  stage: build
  script:
    - cp /srv/env/front.env ./.env
  #  - docker build -f Dockerfile -t front-end:${CI_PIPELINE_ID} .
    - docker build -f Dockerfile -t front-end-ssr:${CI_PIPELINE_ID} .

  only:
    - develop
  tags:
    - front-dev

deploy-develop:
  stage: deploy
  script:
   # - 'env
   #   DEPLOY_NAME=stage
   #   TAG_NAME=${CI_PIPELINE_ID}
   #   REPLICAS=1
   #   docker stack deploy --prune -c docker-stack-deploy.yml dev_frot'
    - 'env
      DEPLOY_NAME=develop
      TAG_NAME=${CI_PIPELINE_ID}
      REPLICAS=1
      docker stack deploy --prune -c docker-stack-deploy-ssr.yml dev_frot_ssr'
  only:
    - develop
  tags:
    - front-dev
  
